# Initialization

In [2]:
import numpy as np

x1 = np.array([1,2,4,5,6,7,8,9])
x2 = np.arange(2,6).reshape(2,2)
x3 = np.arange(1,11,2) # the last one is step
x4 = np.zeros((2,2))
x5 = np.ones((2,2))
x6 = np.eye(3,3)

print(x1)
print(x2)
print(x3)
print(x4)
print(x4)
print(x6)


[1 2 4]
[[2 3]
 [4 5]]
[1 3 5 7 9]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Slice the matrix
``x[start:stop:step]``
range [begin,end)
       
## One dimensional subarrays

In [4]:

x1[-1] # negative number browses from back
x1[:2] # first 5 elements
x1[2:] # elemetns after index 5
x1[2:4] # elements from [Begin,end)

# starts from 1, step 2, every other elements starting at index 1
# step can be negative, in reverse order
x1[1::2] 



array([4])

## Multidimensional subarrays

In [8]:
x2 = np.arange(1,13).reshape(3,4)
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# Index starts from 0, range [begin,end)
x2[:2,:3] # two rows, three columns


array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
x2[1:2,2:4]

array([[7, 8]])

In [13]:
# reverse order
x2[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### Accessing array rows and columns
One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``)
> note the result is ``row``

In [19]:
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
x2[:,0] # first column

array([1, 5, 9])

In [15]:
x2[:,1] # second colum

array([ 2,  6, 10])

In [16]:
x2[2,:]

array([ 9, 10, 11, 12])

In the case of ``row access``, the ``empty slice`` can be ``omitted`` for a more compact syntax:

In [20]:
x2[0]

array([1, 2, 3, 4])

## Subarrays as no copy views
subarrays 是对原array的引用

In [23]:
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
x2_sub = x2[:2,:2]
x2_sub

array([[1, 2],
       [5, 6]])

In [28]:
x2_sub[0,0] = 99
x2_sub

array([[99,  2],
       [ 5,  6]])

In [29]:
x2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Creating copies of arrays

In [30]:
x2_sub_copy=x2[:2,:2].copy()
x2_sub_copy

array([[99,  2],
       [ 5,  6]])

In [31]:
x2_sub_copy[0,0] = 1
x2_sub_copy

array([[1, 2],
       [5, 6]])

In [32]:
x2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Reshaping of arrays
- the reshape method will use a ``no-copy`` view of the initial array
- Another common reshaping pattern is the conversion of a **one-dimensional** array into a **two-dimensional row or column matrix**. This can be done with the reshape method, or more easily done by making use of the ``newaxis`` keyword within a ``slice operation``

In [36]:
x = np.array([1,2,3,4])
x.reshape((1,4))

array([[1, 2, 3, 4]])

In [38]:
b = x[np.newaxis,:] # row vector
b.shape
b

array([[1, 2, 3, 4]])

In [39]:
c = x[:,np.newaxis] # column vector
c

array([[1],
       [2],
       [3],
       [4]])

# Array Concatenation and Spliting

In [41]:
## Concatenation of arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])


array([1, 2, 3, 3, 2, 1])

In [47]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

> For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:
- vstack, vertical stack （竖直方向上append)
- hstack, horizaontal stack (横向append）

In [49]:
np.vstack([x,y])

array([[1, 2, 3],
       [3, 2, 1]])

In [51]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [52]:
y = np.array([[22],[22]])
np.hstack([grid,y])

array([[ 9,  8,  7, 22],
       [ 6,  5,  4, 22]])

## Splitting of arrays
- np.split
- np.hsplit
- np.vsplit

In [54]:
x = [1,2,3,99,99,3,2,1]
# 3 parts, range [:3],[3:5],[5:]
x1,x2,x3 = np.split(x,[3,5]) # 最后一个参数表示range
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [56]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [58]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


[reference](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)